name: PyTest
on:
  push:
    branches:
      - "*"
    branches-ignore:
      - "features/doc"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zeroc-ice>=3.7
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest .
